begin;
select set_config('mf.test.notification',gen_random_uuid()::text,true);
insert into public.notifications(id,recipient_id,notification_type,title,body) values(current_setting('mf.test.notification')::uuid,'f808b8d1-97ff-4302-adef-4bc8d5b9630b','test','Rollback notification','No delivery; transaction rolls back');
set local role authenticated;
select set_config('request.jwt.claim.sub','f808b8d1-97ff-4302-adef-4bc8d5b9630b',true);
do $$
declare mid uuid:=gen_random_uuid(); priv uuid:=gen_random_uuid(); callid uuid:=gen_random_uuid(); r public.chat_messages; again public.chat_messages; n integer;
room text:='private:6a1fae70-78f8-42eb-a743-507938cdefd1:f808b8d1-97ff-4302-adef-4bc8d5b9630b';
begin
 select * into r from public.send_chat_message(mid,'general','general',null,null,'Rollback message',null,null);
 select * into again from public.send_chat_message(mid,'general','general',null,null,'Rollback message',null,null);
 if r.id<>again.id or r.sender_id<>auth.uid() or r.branch_code<>'B1' then raise exception 'Chat identity or replay incorrect';end if;
 if r.sender_name<>(select full_name from public.profiles where id=auth.uid()) then raise exception 'Sender name not authoritative';end if;
 begin perform public.send_chat_message(mid,'general','general',null,null,'Changed',null,null);raise exception 'Changed replay accepted';exception when raise_exception then if sqlerrm<>'Message id already used with different content' then raise;end if;end;
 begin perform public.send_chat_message(gen_random_uuid(),'wrong-room','general',null,null,'Wrong room',null,null);raise exception 'Wrong room accepted';exception when raise_exception then if sqlerrm<>'Room identity does not match participants' then raise;end if;end;
 begin perform public.send_chat_message(gen_random_uuid(),'general','general',null,null,'Wrong file','file','other-user/file');raise exception 'Foreign attachment accepted';exception when raise_exception then if sqlerrm<>'Attachment must belong to sender' then raise;end if;end;
 begin perform public.send_chat_message(gen_random_uuid(),'team:invented','team',null,'invented','Invented team',null,null);raise exception 'Invented team accepted';exception when raise_exception then if sqlerrm<>'Registered team in your branch required' then raise;end if;end;
 perform public.send_chat_message(priv,room,'private','6a1fae70-78f8-42eb-a743-507938cdefd1',null,'Private rollback',null,null);
 insert into public.call_invitations(id,room_id,caller_id,callee_id,call_type,status) values(callid,room,auth.uid(),'6a1fae70-78f8-42eb-a743-507938cdefd1','audio','ringing');
 if public.can_signal_call('mf-call-'||callid::text) then raise exception 'Ringing call allowed signaling';end if;
 begin update public.call_invitations set status='accepted' where id=callid;raise exception 'Caller accepted own invitation';exception when raise_exception then if sqlerrm<>'Call transition not allowed for this participant' then raise;end if;end;
 insert into public.notification_preferences(user_id,general_enabled,payment_enabled,followup_enabled) values(auth.uid(),false,true,false)
 on conflict(user_id) do update set general_enabled=false,payment_enabled=true,followup_enabled=false;
 if not exists(select 1 from public.notification_preferences where user_id=auth.uid() and not general_enabled and payment_enabled and not followup_enabled) then raise exception 'Preferences not persisted';end if;
 update public.notifications set is_read=true where id=current_setting('mf.test.notification')::uuid;
 if not exists(select 1 from public.notifications where id=current_setting('mf.test.notification')::uuid and is_read) then raise exception 'Read receipt missing';end if;
 begin update public.notifications set body='Forged' where id=current_setting('mf.test.notification')::uuid;raise exception 'Notification body changed';exception when raise_exception then if sqlerrm<>'Notification payload is immutable' then raise;end if;end;
 perform set_config('request.jwt.claim.sub','c92479bb-d9c3-496c-80c9-4a0af8c6268b',true);
 select count(*) into n from public.chat_messages where id=priv;if n<>0 then raise exception 'Unrelated manager reads private chat';end if;
 select count(*) into n from public.notifications where id=current_setting('mf.test.notification')::uuid;if n<>0 then raise exception 'Unrelated manager reads notification';end if;
 perform set_config('request.jwt.claim.sub','6a1fae70-78f8-42eb-a743-507938cdefd1',true);
 select count(*) into n from public.chat_messages where id=priv;if n<>1 then raise exception 'Private recipient cannot read';end if;
 update public.call_invitations set status='accepted' where id=callid;
 if not public.can_signal_call('mf-call-'||callid::text) then raise exception 'Accepted participant cannot signal';end if;
 perform set_config('request.jwt.claim.sub','6693ab34-0188-4a86-871d-b12554003894',true);
 if public.can_signal_call('mf-call-'||callid::text) then raise exception 'Archive owner can signal outside participants';end if;
 perform set_config('request.jwt.claim.sub','f808b8d1-97ff-4302-adef-4bc8d5b9630b',true);
 if not public.can_signal_call('mf-call-'||callid::text) then raise exception 'Accepted caller cannot signal';end if;
 update public.call_invitations set status='ended' where id=callid;
 if public.can_signal_call('mf-call-'||callid::text) then raise exception 'Ended call allows new signaling access';end if;
 begin update public.call_invitations set status='accepted' where id=callid;raise exception 'Ended call reopened';exception when raise_exception then if sqlerrm<>'Call transition not allowed for this participant' then raise;end if;end;
 perform set_config('request.jwt.claim.sub','6693ab34-0188-4a86-871d-b12554003894',true);
 update public.profiles set is_active=false where id='f808b8d1-97ff-4302-adef-4bc8d5b9630b';
 perform set_config('request.jwt.claim.sub','f808b8d1-97ff-4302-adef-4bc8d5b9630b',true);
 select count(*) into n from public.chat_messages where id=mid;if n<>0 then raise exception 'Disabled user sees chat';end if;
 select count(*) into n from public.notifications where id=current_setting('mf.test.notification')::uuid;if n<>0 then raise exception 'Disabled user sees notifications';end if;
 select count(*) into n from public.notification_preferences where user_id=auth.uid();if n<>0 then raise exception 'Disabled user sees preferences';end if;
end $$;
select 'PASS: chat replay/identity/room/attachments, private isolation, durable preferences/read, call state and signaling authorization; all rolled back, no messages delivered' as result;
rollback;
